#!/bin/bash
mdl=$(brightnessctl -l | grep kbd | awk -F"'" '{print $2}')
max=$(brightnessctl -d $mdl m)
min=0
slee=0.08
lvl=50
lvl1=20

while true; do
    while true; do
        curr=$(brightnessctl -d $mdl g)
        if [ "$curr" -ge "$max" ]; then
            break
        fi
        brightnessctl -d $mdl s +$lvl
        sleep $slee
    done

    while true; do
        curr=$(brightnessctl -d $mdl g)
        if [ "$curr" -le "$min" ]; then
            break
        fi
        brightnessctl -d $mdl s $lvl1-
        sleep $slee
    done
done
