#!/bin/bash
MDL=$(brightnessctl -l | grep kbd | awk -F"'" '{print $2}')
MAX=$(brightnessctl -d $MDL m)
MIN=0
SLEE=0.08
LVL=50
LVL1=20

while true; do
    while true; do
        curr=$(brightnessctl -d $MDL g)
        if [ "$curr" -ge "$MAX" ]; then
            break
        fi
        brightnessctl -d $MDL s +$LVL
        sleep $SLEE
    done

    while true; do
        curr=$(brightnessctl -d $MDL g)
        if [ "$curr" -le "$MIN" ]; then
            break
        fi
        brightnessctl -d $MDL s $LVL1-
        sleep $SLEE
    done
done
